config/routes.rb
Rails.application.routes.draw do
  devise_for :employee_authenticates
  require 'sidekiq/web'
  root "blogs#index"

  resources :companies
  resources :blogs
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :employee_profiles do
    scope module: :employee_profiles do
      resource :leave, only: %i[show destroy]
    end
  end

  namespace :api do
    resources :health_check, only: :index
  end
  mount Sidekiq::Web, at: "/sidekiq"
  mount Flipper::UI.app(Flipper) => '/flipper'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get "*anything" => "errors#not_found"
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id              :bigint           not null, primary key
#  employee_id     :bigint
#  title(タイトル) :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_blogs_on_employee_id  (employee_id)
#
# Foreign Keys
#
#  fk_rails_...  (employee_id => employees.id)
#
class Blog < ApplicationRecord
  # Relations
  belongs_to :employee

  # Validations
  validates :title, presence: true

  # Callbacks

  # Delegates

  # Scopes

  # Methods
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_employee_authenticate!, only: %i[ new edit create update destroy]
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: "Blog was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "Blog was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    redirect_to root_path, notice: "Blog was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title).merge(employee_id: current_employee_authenticate.employee_id)
    end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td>
        <% if blog.employee.active? %>
          <%= link_to blog.employee.employee_profile&.name, employee_profile_path(id: blog.employee.employee_profile&.id) %></td>
        <% end %>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>
<%= link_to 'Set Profile', new_employee_profile_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>